[[zimg]]
arch = "aarch64"
git-tree-sha1 = "b385be31631699d076d3876fb6c3e20bcd3d0e5e"
os = "macos"

    [[zimg.download]]
    sha256 = "71e5492225d357b1153b69570001be38ab10c2481ee5d5bae17f35f6859769b7"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.aarch64-apple-darwin.tar.gz"
[[zimg]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80a5370f5b8b3260377eb2fa449cfafe138f67fc"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "4d113bf812065324d90bbfb27602d3fa474ff81c7e4738cb674c7cdedd656a96"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[zimg]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e15835fe0cfba6845e37928f37aa399d066d8fd"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "1fc316906cca004cd821c990b2f3f35093165ced1b7e75101256984b9d17d76e"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[zimg]]
arch = "aarch64"
git-tree-sha1 = "f25af6b6681f800437be4c963855e52e6ef23200"
os = "freebsd"

    [[zimg.download]]
    sha256 = "78f5e42e14bfa070ff87c5c00acff407eb0751ec4087398a4ca38db20f3076f8"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.aarch64-unknown-freebsd.tar.gz"
[[zimg]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eccf3852b45d562b87715e6521cd6cd6eaa4bbbc"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "e7499d50a20e2bbc7918e40cef56285ca2365ae7dbe0b9f75dc06677c26bae09"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[zimg]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38af828ed24fba26860112bdd5f5fb7bc9520ec4"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "5e5813fe129321ce9ecc638e98f3f254c3195a4090a7ba446e2af62fc4337dc5"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[zimg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "611b8f88f8ea14635aaf69f820b2603d7a1482e3"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "d243d4b037acdd5fba5ebdb0f384ddd38ffa63cce74bf7e3b30b1b3a7a115efa"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[zimg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5106158e1d7923625433eb807b29958f63bd930a"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "e8b2180cc3a3ac1700f02bb7ffc309cf58ec67b66dcba1a8db7337e9e7900628"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67b129b66d4255e9943e36024bdc8c4e8398fb45"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "7f319dc9606441a8686ddfda93693a2f28cac1cda5f06e5cec06bff280a53b51"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.i686-linux-gnu-cxx11.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a78c43ec7cf1ad784733e668e794b14305c99693"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "6fbe6166eba57fe37facd913242bcbf0c58b25564da80be107fe9ebeb1268978"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.i686-linux-musl-cxx11.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f50bac7687a891e15a5b4a2a5e3fb7ca7f2aba3"
os = "windows"

    [[zimg.download]]
    sha256 = "619f8db8e095d9b611dd59242fd9a8ed78b023be9d3b73cc5c4bbc7050d82940"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[zimg]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "884f26f26295dd4bb926d3d3ae9c98c25da38359"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "59aa1df1f5a0466f8851b32b97c13ebda85ec12219322071793752930f43d1b3"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[zimg]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "760d58896b2eaa937b8d3221285ed25f8a222c6e"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "cf8bc30b1474fe4515cf55cbf9f2dcab3dc812b0674bbb4f8073dcbe6fe14e2c"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.riscv64-linux-gnu-cxx11.tar.gz"
[[zimg]]
arch = "x86_64"
git-tree-sha1 = "e7ee1154295b3b0b6b6f52d9e5c4a55e91c61750"
os = "macos"

    [[zimg.download]]
    sha256 = "5175853a6dd18d7ef15b6daa6b370d1fc2bee7ea4b1a2e5b80722b6d56dc4b10"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.x86_64-apple-darwin.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "443cbde56824011d5a3f46a0587be4a230822b9f"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "cb7c85d35756d0a1f6400d118ec334f79668413467c0856573dc9fb270d6c0c0"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35d86943c50dc6f85e943cfd67781a264cfea01c"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "278c8575433beef9e5b29041470a86b4303a9812677c76a8cc46caf2fbe02644"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[zimg]]
arch = "x86_64"
git-tree-sha1 = "c26db3a11c07279d32718434328434389ba85834"
os = "freebsd"

    [[zimg.download]]
    sha256 = "2c9868d8868d978596b879bdd4f33b23b4ac86869b7041c792ff060404464932"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.x86_64-unknown-freebsd.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dab11ccede12d5d33cfa2030183b54f00ddf5d5"
os = "windows"

    [[zimg.download]]
    sha256 = "08d79302c3bb9b9aa00e9937c6bb6582a8071f3780ebbd220683ea9addb596fb"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.6+0/zimg.v3.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
