[[zimg]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f44bb49532814c8704d082e97282c5cd26b743f1"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "b75c173be776f56aa7dab2f11f9fb0f7f7eabe335428c3a6b200dd7fbf5b3a10"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[zimg]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b138707ea59086adbea17a4a741374c052a442e3"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "89a60f8bbf812dcaa71f0fa0ce52e0c9ff98034e86b3817ffa5123801741d1d7"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[zimg]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ce1471303cb28447d26650891382e0caa8848aa"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "7ade442decadf7bfe58fc41c366bc763c48ec589c1f972738883db41e44ed516"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[zimg]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1efe419f89a9dcd8c9e955c1b983bbe974dff61d"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "68d1c31bf85ec4ab9e798d6d24273435e1147d7d49a0f47bda3a7f579b6a0e69"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[zimg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02f1cb4ac1a85ba8ca65581a09a0800c38ba5597"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "b31f82e40960b79e5e2410fc9e123e4e6ee5a6c1a6a25f0d8ec761a82988fa99"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[zimg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c13e5de9cc294084ae82e42ca705caa9bd368adf"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "1bc8a9ef5824fb603d3c9c5401c1eda614e646192aae5e861bf15e39a5378727"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[zimg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92ebce2e5e82285eca24c2af2a0375a097673633"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "9696e076c5b1ffe028a62a80b8677d964a7586bec76ab4cfa7ce8f40efac3d6b"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[zimg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "231549f8d859a52bf2c725f1ea6b825963e740af"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "00458a35cfbd87b15d0ccf7ebd33a32def6de9e7fb667cb09259c1f731359f16"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e8c75bf72350135f0ad2855dc3aa68df07f9a46"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "a2cb89469b365079f768c5e0fad17ee06fec0f49cc730d09f7617d132c5b364b"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.i686-linux-gnu-cxx03.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da617ab8f5b7d0d752539247a5197ab50ba79ddd"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "6c20e7008dae831206d4c697964b1d9467c6ad10cededf279c6038da938b1d3d"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.i686-linux-gnu-cxx11.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4110faad0bac2b878567382cbcf7a20185660339"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "c9032c5043201045a44ce88d582a748b3edb1e8a75405a5a21c309f94f1f8263"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.i686-linux-musl-cxx03.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74d12943eba3ec2235daea179fc5e1c01065ebba"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "b1fc845de44203099590e1e6f37419125354aae5dfb053a50cab2f849492ba80"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.i686-linux-musl-cxx11.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d02a365c5345071ddf8b3ba3b9d38b95d42d870"
os = "windows"

    [[zimg.download]]
    sha256 = "add6b9f04352fa4a04b9494b034c5d95ad588ff4dd5925619c4f80258e3c5612"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.i686-w64-mingw32-cxx03.tar.gz"
[[zimg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ab734c4a6f85ead6193b4bb1bb1da39e93dc7ac"
os = "windows"

    [[zimg.download]]
    sha256 = "4f02a31ef2714297832d78932d15e0c5447cf7f29ba34d5f1db6bc4ee5f5051a"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.i686-w64-mingw32-cxx11.tar.gz"
[[zimg]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "898cc4f05bf3a4eaa5f608de10179bcaabdeb14c"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "94813cf1032f8b6499732c0c7cd7dab47dbd146950598f2ebfa9e2da27380698"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[zimg]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f0d60ff5969958c3edd4ca0d2d4a6abd243ba72"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "5353943bdbde00795d83973003bd2ff89abf4783991e05488402b3b957423788"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[zimg]]
arch = "x86_64"
git-tree-sha1 = "d2e86ca319b4a5421a4675cc29b2f5f23187f532"
os = "macos"

    [[zimg.download]]
    sha256 = "da4abc7e493a9079e58de342c9a79cc93b5bac233f71ad9c7f6e8735fcaab187"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.x86_64-apple-darwin.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aab145c1070b146a51d313322b1e7853fce51bc"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "1ca7a17872d7f3f826df16d4036b6d2709f9e56b31cdb6a85ceb273e168e3000"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.x86_64-linux-gnu-cxx03.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37b04c8b9545ee82e7b48defd3b46d7e5e4302e1"
libc = "glibc"
os = "linux"

    [[zimg.download]]
    sha256 = "b4790f0161b74023d86253b22277187ce18852e7984588d877df4807343bb7bc"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.x86_64-linux-gnu-cxx11.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6c4074884663664e3c0fb21e9f2810ee7f6d4fc"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "292e3f8d7a32f88008133f3176a20c380eb8d762f0d1731309186310358eaab6"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.x86_64-linux-musl-cxx03.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "810c2d878f3fcc2c5b57123c04f4e3c59d79569d"
libc = "musl"
os = "linux"

    [[zimg.download]]
    sha256 = "386090ae15b4c1b4a772e4510582aba250d62febca8281f9c7e2ba9eb74f8c4b"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.x86_64-linux-musl-cxx11.tar.gz"
[[zimg]]
arch = "x86_64"
git-tree-sha1 = "49c42f4e07a39142bf320346e609db718e937219"
os = "freebsd"

    [[zimg.download]]
    sha256 = "2b4270d4849be5692d847bd3178be182942e1df2bc5a7eb2bfc13d46709d1070"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.x86_64-unknown-freebsd.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "249a8d7bcf6afeb91da4cd60cbdaa7e0e8170bc7"
os = "windows"

    [[zimg.download]]
    sha256 = "2c8e894fc5f881bd0db50538ebe5865916ec5283231c072523f38e78013dde1e"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[zimg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8484161005ebde580b1467d43a4c3dd7c7d6014e"
os = "windows"

    [[zimg.download]]
    sha256 = "cfa8541b0193e641b88705302c5c165f63a960ca1890a9b1c9d960b077eba2de"
    url = "https://github.com/JuliaBinaryWrappers/zimg_jll.jl/releases/download/zimg-v3.0.3+0/zimg.v3.0.3.x86_64-w64-mingw32-cxx11.tar.gz"
