# Autogenerated wrapper script for zimg_jll for aarch64-apple-darwin
export libzimg

JLLWrappers.@generate_wrapper_header("zimg")
JLLWrappers.@declare_library_product(libzimg, "@rpath/libzimg.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libzimg,
        "lib/libzimg.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
