# Autogenerated wrapper script for zimg_jll for i686-w64-mingw32-cxx03
export libzimg

JLLWrappers.@generate_wrapper_header("zimg")
JLLWrappers.@declare_library_product(libzimg, "libzimg-2.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libzimg,
        "bin\\libzimg-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
